### PR TITLE
Support 0.6

### PR DESCRIPTION
**Pull request by nsmith5**
Adds support for Julia v0.6.x and removes support for versions 0.4 and 0.5. Also contains some other small fixes:
 - Applies patches from PR #15 to prevent making the package dirty under usage
 - Adds patches to the README
 - Add some more tests

### CODE REVIEW

**Comment by nsmith5** [comment]
Seems to work on an older version of DataFrames. Updates in progress..

**Comment by randyzwitch** [comment]
In the future, you should still have someone review your PR.

**Comment by nsmith5** [comment]
Right, sorry about that. I'm happy revert if you'd like to review.

**Comment by randyzwitch** [comment]
No, it’s fine for this one. The tests passed and it was severely out-of-date. Just for the future give people a chance to comment (48-72hrs maybe?)

**Comment by nsmith5** [comment]
Absolutely, well do!

**Pull request merged**
