### PR TITLE
Fix 0.4 deprecations

### PR DESCRIPTION
**Pull request by hayd**
String -> AbstractString and Union(..) -> Union{..}

Also use do notation.

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Any thoughts about the failures?

**Comment by hayd** [comment]
Part of this is #12 I think, they seem to be timeouts. Not sure about the precompile, it works locally for me:

    ERROR: LoadError: LoadError: __precompile__(true) but require failed to create a precompiled cache file

**Comment by sbromberger** [comment]
The timeout failures are almost certainly #12.

**Comment by nsmith5** [comment]
Good points in this PR have been addressed. Closing due to being outdated.

**Pull request closed without merging**
